
blank_issues_enabled: true
contact_links:
  - name: Feature request
    url: https://console.serendb.com/app/projects?modal=feedback
    about: For feature requests in the SerenDB product, please submit via the feedback form on `https://console.serendb.com`
